### ISSUE TITLE
Migration to Python 3.9 or 3.10

### ISSUE THREAD

**Issue by Reidmen** [finsberg/ldrb#97]
Just wondering, Python 3.8 is slowly getting into its [final phases of support](https://devguide.python.org/versions/). Also new images of legacy fenics are built with 3.10 at least.

Shall we start enforcing 3.10 for this package?

Some pros about it are along the side of built-in typing capabilities.

**Comment by finsberg** [comment]
I think that as long as python3.8 is not EOL, we should support it. 
Are there any specific features you are looking for? 
I am on board with using
```python
from __future__ import annotations
```
to get some of the more recent typing capabilities such as using e.g `list[int]` instead of `typing.List[int]` or using `|` instead of `typing.Union`. I am also OK with adding [typing_extensions](https://github.com/python/typing_extensions/tree/main) as a dependency.

My plan is alos to start the work on migrating this package to FEniCSx during the spring next year and in that package I will probably only support python3.10 and above.

**Comment by Reidmen** [comment]
From my side, typing is the main thing. But I agree regarding the EOL, better support it. 

Your solution is the best one, just get the annotation from `__future__`
